
package uk.org.taverna.astro.vorepo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import net.ivoa.wsdl.registrysearch.v1_0.ErrorResp;
import net.ivoa.wsdl.registrysearch.v1_0.NotFoundResp;
import net.ivoa.wsdl.registrysearch.v1_0.OpUnsupportedResp;
import net.ivoa.wsdl.registrysearch.v1_0.RegistrySearchPortType;

import uk.org.taverna.astro.vorepo.RegistryInterface;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-16T15:56:00.254+01:00
 * Generated source version: 2.5.2
 * 
 */
public final class RegistrySearchPortType_RegistrySearchPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ivoa.net/wsdl/RegistryInterface/v1.0", "RegistryInterface");

    private RegistrySearchPortType_RegistrySearchPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RegistryInterface.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RegistryInterface ss = new RegistryInterface(wsdlURL, SERVICE_NAME);
        RegistrySearchPortType port = ss.getRegistrySearchPort();  
        
        {
        System.out.println("Invoking search...");
        net.ivoa.wsdl.registrysearch.v1.Search _search_search = null;
        try {
            net.ivoa.wsdl.registrysearch.v1.SearchResponse _search__return = port.search(_search_search);
            System.out.println("search.result=" + _search__return);

        } catch (ErrorResp e) { 
            System.out.println("Expected exception: ErrorResp has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking xQuerySearch...");
        net.ivoa.wsdl.registrysearch.v1.XQuerySearch _xQuerySearch_xQuerySearch = null;
        try {
            net.ivoa.wsdl.registrysearch.v1.XQuerySearchResponse _xQuerySearch__return = port.xQuerySearch(_xQuerySearch_xQuerySearch);
            System.out.println("xQuerySearch.result=" + _xQuerySearch__return);

        } catch (ErrorResp e) { 
            System.out.println("Expected exception: ErrorResp has occurred.");
            System.out.println(e.toString());
        } catch (OpUnsupportedResp e) { 
            System.out.println("Expected exception: OpUnsupportedResp has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking keywordSearch...");
        net.ivoa.wsdl.registrysearch.v1.KeywordSearch _keywordSearch_keywordSearch = null;
        try {
            net.ivoa.wsdl.registrysearch.v1.SearchResponse _keywordSearch__return = port.keywordSearch(_keywordSearch_keywordSearch);
            System.out.println("keywordSearch.result=" + _keywordSearch__return);

        } catch (ErrorResp e) { 
            System.out.println("Expected exception: ErrorResp has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getIdentity...");
        java.lang.Object _getIdentity_getIdentity = new java.lang.Object();
        try {
            net.ivoa.wsdl.registrysearch.v1.ResolveResponse _getIdentity__return = port.getIdentity(_getIdentity_getIdentity);
            System.out.println("getIdentity.result=" + _getIdentity__return);

        } catch (ErrorResp e) { 
            System.out.println("Expected exception: ErrorResp has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getResource...");
        net.ivoa.wsdl.registrysearch.v1.GetResource _getResource_getResource = null;
        try {
            net.ivoa.wsdl.registrysearch.v1.ResolveResponse _getResource__return = port.getResource(_getResource_getResource);
            System.out.println("getResource.result=" + _getResource__return);

        } catch (ErrorResp e) { 
            System.out.println("Expected exception: ErrorResp has occurred.");
            System.out.println(e.toString());
        } catch (NotFoundResp e) { 
            System.out.println("Expected exception: NotFoundResp has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
