<?xml version="1.0" encoding="UTF-8"?> <!-- uk.org.taverna.astro.vorepo -->
<definitions name="searchableRegistry"
	targetNamespace="http://taverna.org.uk/astro/wsdl/RegistrySearch"
	xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ris="http://www.ivoa.net/wsdl/RegistrySearch/v1.0"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://taverna.org.uk/astro/vorepo/wsdl"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Dummy search WSDL - as there is no wsdl:service in http://www.ivoa.net/wsdl/RegistrySearch/v1.0. 
		Adapted from http://registry.euro-vo.org/services/RegistrySearch?wsdl -->

	<import location="./RegistrySearch-v1.0.wsdl" namespace="http://taverna.org.uk/astro/vorepo/wsdl"></import>
	<service name="RegistrySearchService">
		<port binding="ris:RegistrySearchSOAP" name="RegistrySearchPortSOAP">
			<!-- To be overridden with different endpoint -->
			<soap:address location="http://localhost/RegistrySearch/ChangeMe" />
		</port>
	</service>
</definitions>


