<?xml version="1.0" encoding="UTF-8"?> <!-- uk.org.taverna.astro.vorepo -->
<definitions name="searchableRegistry"
	targetNamespace="http://taverna.org.uk/astro/wsdl/RegistrySearch"
	xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ris="http://www.ivoa.net/wsdl/RegistrySearch/v1.0"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://taverna.org.uk/astro/vorepo/wsdl"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vds="http://www.ivoa.net/xml/VODataService/v1.0">

	<!-- Dummy search WSDL - as there is no wsdl:service in http://www.ivoa.net/wsdl/RegistrySearch/v1.0. 
		Adapted from http://registry.euro-vo.org/services/RegistrySearch?wsdl -->
	<import location="./RegistrySearch-v1.0.wsdl" namespace="http://taverna.org.uk/astro/vorepo/wsdl"></import>

	<types>
		<xs:schema>
			<!-- Import additional schemas for cone services, etc. -->

			<xs:import namespace="http://www.ivoa.net/xml/ADQL/v1.0"
				schemaLocation="http://www.ivoa.net/xml/ADQL/v1.0" />
			<xs:import namespace="http://www.ivoa.net/xml/ConeSearch/v1.0"
				schemaLocation="http://www.ivoa.net/xml/ConeSearch/v1.0" />
			<xs:import namespace="http://www.ivoa.net/xml/RegistryInterface/v1.0"
				schemaLocation="http://www.ivoa.net/xml/RegistryInterface/v1.0" />
			<xs:import namespace="http://www.ivoa.net/xml/SIA/v1.0"
				schemaLocation="http://www.ivoa.net/xml/SIA/v1.0" />
			<xs:import namespace="http://www.ivoa.net/xml/SLAP/v0.1"
				schemaLocation="http://www.ivoa.net/xml/SLAP/v0.1" />
			<xs:import namespace="http://www.ivoa.net/xml/SSA/v0.4"
				schemaLocation="http://www.ivoa.net/xml/SSA/v0.4" />			
			<xs:import namespace="http://www.ivoa.net/xml/STC/STCcoords/v1.10"
				schemaLocation="http://www.ivoa.net/xml/STC/STCcoords/v1.10" />
			<xs:import namespace="http://www.ivoa.net/xml/STC/STCregion/v1.10"
				schemaLocation="http://www.ivoa.net/xml/STC/STCregion/v1.10" />
			<xs:import namespace="http://www.ivoa.net/xml/VODataService/v1.0"
				schemaLocation="http://www.ivoa.net/xml/VODataService/v1.0" />
			<xs:import namespace="http://www.ivoa.net/xml/VOResource/v1.0"
				schemaLocation="http://www.ivoa.net/xml/VOResource/v1.0" />
			<xs:import namespace="http://www.ivoa.net/xml/VOStandard/v0.1"
				schemaLocation="http://www.ivoa.net/xml/VOStandard/v0.1" />			
		</xs:schema>
	</types>

	<service name="RegistrySearchService">
		<port binding="ris:RegistrySearchSOAP" name="RegistrySearchPortSOAP">
			<!-- To be overridden with different endpoint -->
			<soap:address location="http://localhost/RegistrySearch/ChangeMe" />
		</port>
	</service>
</definitions>


