package uk.org.taverna.astro.vorepo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import net.ivoa.wsdl.registrysearch.v1_0.RegistrySearchPortType;

/**
 * Generated from http://nvo.caltech.edu:8080/carnivore/services?wsdl
 * 
 * 
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-16T15:56:00.444+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "RegistryInterface", 
                  wsdlLocation = "http://www.ivoa.net/wsdl/RegistrySearch/v1.0",
                  targetNamespace = "http://www.ivoa.net/wsdl/RegistryInterface/v1.0") 
public class RegistryInterface extends Service {

    public final static URL WSDL_LOCATION;

    
    public final static QName SERVICE = new QName("http://esavo.esa.int/wsdl/searchableRegistry.wsdl", "RegistrySearchService");
    public final static QName RegistrySearchPort = new QName("http://www.ivoa.net/wsdl/RegistryInterface/v1.0", "RegistrySearchPort");
   
    static {
        URL url = null;
        try {
            url = new URL("http://www.ivoa.net/wsdl/RegistrySearch/v1.0");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegistryInterface.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.ivoa.net/wsdl/RegistrySearch/v1.0");
        }
        WSDL_LOCATION = url;
    }

    public RegistryInterface(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegistryInterface(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistryInterface() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RegistryInterface(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RegistryInterface(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RegistryInterface(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RegistrySearchPortType
     */
    @WebEndpoint(name = "RegistrySearchPort")
    public RegistrySearchPortType getRegistrySearchPort() {
        return super.getPort(RegistrySearchPort, RegistrySearchPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrySearchPortType
     */
    @WebEndpoint(name = "RegistrySearchPort")
    public RegistrySearchPortType getRegistrySearchPort(WebServiceFeature... features) {
        return super.getPort(RegistrySearchPort, RegistrySearchPortType.class, features);
    }

}
